name: Markdown Mimic
author: grokdesigns
description: Action to copy the content of a Markdown file and paste those contents within another Markdown file upon push.
branding:
  icon: "copy"
  color: "gray-dark"

inputs:
  git_username:
    description: "Git username for commits"
    required: true
    default: "github-actions[bot]"
  git_email:
    description: "Git email for commits"
    required: true
    default: "github-actions[bot]@users.noreply.github.com"
  skip_ci:
    description: "Whether to add [no ci] to commit messages"
    required: true
    default: "yes"
  commit_message:
    description: "Commit message for generated files"
    required: true
    default: "🤖 - Generated via Markdown Mimic"
  file_ext:
    description: "File extension for output files"
    required: true
    default: "md"
  output_folder:
    description: "Folder to output generated files"
    required: true
    default: "output"
  input_folder:
    description: "Folder containing template files"
    required: true
    default: "templates"
  branch_name:
    description: "Branch name to associate with the commit"
    required: true
    default: "main"
  overwrite_original:
    description: "Overwrite originals or create new copies in output folder."
    required: true
    default: "1"
    
runs:
  using: "docker"
  image: ./Dockerfile
